kind: PersistentVolume
apiVersion: v1
metadata:
  name: ftp-pv-volume
  labels:
    type: local
spec:
  storageClassName: ftp
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/ftp_data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ftp-pv-claim
spec:
  storageClassName: ftp
  selector:
    matchLabels:
      type: local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
