apiVersion: v1
kind: Service
metadata:
  name: ftp
  labels:
    app: ftp
spec:
  type: ClusterIP
  ports:
  - port: 20
    name: ftp-data
  - port: 21
    name: ftp
  - port: 40000
    name: ftp-data-pasv
  selector:
    app: ftp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftp
spec:
  selector:
    matchLabels:
      app: ftp
  template:
    metadata:
      labels:
        app: ftp
    spec:
      containers:
      - name: ftp
        image: ftp-kube:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 20
          protocol: TCP
        - containerPort: 21
          protocol: TCP
        - containerPort: 40000
          protocol: TCP
        env:
        - name: USER_NAME
          value: "toyota" # for Keyence
        - name: USER_PASSWD
          value: "Toyota2019!" # for Keyence
        - name: FTP_PASV_MIN_PORT
          value: "40000"
        - name: FTP_PASV_MAX_PORT
          value: "40000"
        volumeMounts:
        - name: ftp-storage
          mountPath: /data
        - name: ftp-conf
          mountPath: /etc/vsftpd/vsftpd.conf
        - name: ftp-log
          mountPath: /var/log
      volumes:
      - name: ftp-storage
        hostPath:
          path: /var/lib/aion/prj/Data/ftp_data
      - name: ftp-conf
        hostPath:
          path: /var/lib/aion/prj/mnt/ftp_conf/vsftpd.conf
      - name: ftp-log
        hostPath:
          path: /var/lib/aion/prj/mnt/ftp_log

